kind: pipeline
type: ssh
name: default

server:
  host: 
    from_secret: CURRENT_HOST
  user: root
  password:
    from_secret: SSH_PWD

steps:
- name: deploy
  commands:
    - docker-compose up -d --force-recreate
    - docker ps