kind: pipeline
type: docker
name: default


steps:
  - name: scp
    image: appleboy/drone-scp
    settings:
      debug: true
      source:
        - ./
      host:
        from_secret: CURRENT_HOST
      username: root
      port: 22
      password:
        from_secret: SSH_PWD
      target: /data/app/send

  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: CURRENT_HOST
      username: root
      password:
        from_secret: SSH_PWD
      port: 22
      command_timeout: 2m
      script:
        - cd /data/app/send
        - npm config set registry https://registry.npmmirror.com/
        - npm install yarn -g
        - rm  -rf .postcssrc
        - yarn install
        - yarn run build
        - mc cp local/config/send/config.json /data/app/send/dist/server/config.json
        - docker stop send
        - docker rm send
        - docker-compose up -d 
        - docker-compose logs
