kind: pipeline
type: ssh
name: deploy-nginx

server:
  host:
    from_secret: CURRENT_HOST
  user: root
  password:
    from_secret: SSH_PWD

steps:
  - name: build and deploy
    commands:
      - mkdir -p /data/app/send
      - cp -r ./* /data/app/send
      - cd /data/app/send
      - mc cp local/config/send/config.json /data/app/send/dist/server/config.json
      - npm config set registry https://registry.npmmirror.com/
      - npm install yarn -g
      - yarn install
      - yarn run build
      - docker stop send
      - docker rm send
      - docker-compose up -d 