version: "3"
services:
  redis:
    image: redis
    container_name: ff-send-redis
    ports:
      - 27125:6379
  nodejs:
    image: node:16.7.0
    container_name: ff-send-server
    working_dir: /usr/local/src/server
    volumes:
      - ./:/usr/local/src/server
      - ./logs:/usr/local/src/server/logs
    ports:
      - "3004:3000"
    command: ["/bin/sh", "-c", "ls && npm run start"]
networks:
  ff-send:
    driver: bridge
